runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
env_variables:
  CALLBACK_BASE_URI: https://[your-app].appspot.com
  TWITTER_APP_KEY: [YOUR KEY]
  TWITTER_APP_SECRET: [YOUR SECRET]
libraries:
- name: ssl
  version: latest
